name: Check merge
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  no-weekend-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Check for downtimes
      uses: ka7eh/no-weekend-merge@v0.1
      with:
        tz: '-5'
        mon: '00:00-23:59'
        tue: '00:00-23:59'
        wed: '00:00-23:59'
        thu: '00:00-23:59'
        fri: '00:00-23:59'
        sat: '00:00-23:59'
        sun: '00:00-23:59'
